spring:
  application:
    name: tmdb_app
  mvc:
    webjars-path-pattern: /webjars/**
  web:
    resources:
      add-mappings: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    url: /v3/api-docs
  api-docs:
    enabled: true
    path: /v3/api-docs

server:
  port: 8080

tmdb:
  base-url: https://api.themoviedb.org/3
  api-key: ${TMDB_API_KEY}
  connect-timeout-ms: 3000
  read-timeout-ms: 5000